server.port=8080
spring.application.name=booking-logic

cors.allowed-origins=http://localhost:63342
# Ersätt med ett slumpmässigt värde på minst 32 tecken, lägg aldrig detta i git i produktion
jwt.secret=AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
jwt.expiration=3600000 
# one hour limit
logging.level.org.springframework.security=DEBUG

spring.datasource.url=jdbc:mysql://localhost:3306/booking_db
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=password

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

